### ISSUE TITLE
URL for vcm_wegith_complexSemantics.pt in large_files.yml seems corrupted.

### ISSUE THREAD

**Issue by turtleizzy** [SSTDV-Project/VCM#1]
The link provided in large_files.yml returns 403.

https://github.com/Ahn-Ssu/VCM/blob/main/weights/large_files.yml#L12

**Comment by Ahn-Ssu** [comment]
Hi, @turtleizzy 

We've checked the permission to access the weight file.
Could you try it again? 

Thank you for your interest.

**Comment by turtleizzy** [comment]
> Hi, @turtleizzy
> 
> We've checked the permission to access the weight file. Could you try it again?
> 
> Thank you for your interest.

Thank you so much for your quick response. The link is working now.
